export const Productdata = [
  {
    id: 1,
    image: "/productpic/thumbnail.png",
    title: "Essence Mascara Lash Princess",
    category: "Beauty",
    price: 9.27,
    saleprice: 9.99,
    quantity: 1,
    about:
      "The Essence Mascara Lash Princess is a volumizing and lengthening mascara. It offers a dramatic lash look with a long-lasting, cruelty-free formula.",
  },
  {
    id: 2,
    image: "/productpic/thumbnail (1).png",
    title: "Eyeshadow Palette with Mirror",
    category: "Beauty",
    price: 9.27,
    saleprice: 9.99,
    quantity: 1,
    about:
      "This Eyeshadow Palette comes with a built-in mirror and a variety of shades to create stunning eye looks, perfect for daily and party wear.",
  },
  {
    id: 3,
    image: "/productpic/thumbnail (2).png",
    title: "Powder Canister",
    category: "Beauty",
    price: 9.27,
    saleprice: 9.99,
    quantity: 1,
    about:
      "A finely milled setting powder that helps set makeup and control shine, providing a lightweight and matte finish.",
  },
  {
    id: 4,
    image: "/productpic/thumbnail (3).png",
    title: "Red Lipstick",
    category: "Beauty",
    price: 9.27,
    saleprice: 9.99,
    quantity: 1,
    about:
      "A classic red lipstick with a smooth, long-lasting formula that provides intense color payoff for a bold look.",
  },
  {
    id: 5,
    image: "/productpic/thumbnail (4).png",
    title: "Red Nail Polish",
    category: "Beauty",
    price: 9.27,
    saleprice: 9.99,
    quantity: 1,
    about:
      "A glossy red nail polish that delivers a high-shine finish and long-lasting wear, perfect for any occasion.",
  },
  {
    id: 6,
    image: "/productpic/thumbnail (5).png",
    title: "Calvin Klein CK One",
    category: "Fragrance",
    price: 29.99,
    saleprice: 34.99,
    quantity: 1,
    about:
      "A unisex fragrance by Calvin Klein with a fresh, citrusy scent, perfect for everyday wear.",
  },
  {
    id: 7,
    image: "/productpic/thumbnail (6).png",
    title: "Chanel Coco Noir Eau De Parfum",
    category: "Fragrance",
    price: 99.99,
    saleprice: 109.99,
    quantity: 1,
    about:
      "A luxurious fragrance with notes of citrus, jasmine, and patchouli, creating a sophisticated and elegant scent.",
  },
  {
    id: 8,
    image: "/productpic/thumbnail (7).png",
    title: "Dior J'adore",
    category: "Fragrance",
    price: 89.99,
    saleprice: 99.99,
    quantity: 1,
    about:
      "A floral and fruity fragrance with notes of ylang-ylang, jasmine, and rose, offering a timeless and elegant aroma.",
  },
  {
    id: 9,
    image: "/productpic/thumbnail (8).png",
    title: "Dolce Shine Eau de Parfum",
    category: "Fragrance",
    price: 79.99,
    saleprice: 89.99,
    quantity: 1,
    about:
      "A bright and cheerful perfume with fresh mango, jasmine, and sandalwood notes, ideal for a summer day.",
  },
  {
    id: 10,
    image: "/productpic/thumbnail (9).png",
    title: "Gucci Bloom Eau de Parfum",
    category: "Fragrance",
    price: 99.99,
    saleprice: 109.99,
    quantity: 1,
    about:
      "A rich, white floral fragrance with natural tuberose and jasmine, celebrating modern femininity.",
  },
  {
    id: 11,
    image: "/productpic/thumbnail (10).png",
    title: "Annibale Colombo Bed",
    category: "Furniture",
    price: 1200.0,
    saleprice: 1300.0,
    quantity: 1,
    about:
      "A handcrafted wooden bed with a luxurious finish, designed for comfort and durability.",
  },
  {
    id: 12,
    image: "/productpic/thumbnail (11).png",
    title: "Annibale Colombo Sofa",
    category: "Furniture",
    price: 1500.0,
    saleprice: 1600.0,
    quantity: 1,
    about:
      "A premium Italian-made sofa offering exceptional comfort and elegant craftsmanship.",
  },
  {
    id: 13,
    image: "/productpic/thumbnail (12).png",
    title: "Bedside Table African Cherry",
    category: "Furniture",
    price: 250.0,
    saleprice: 299.99,
    quantity: 1,
    about:
      "A stylish bedside table made of African Cherry wood, featuring a smooth finish and spacious storage.",
  },
  {
    id: 14,
    image: "/productpic/thumbnail (13).png",
    title: "Knoll Saarinen Chair",
    category: "Furniture",
    price: 850.0,
    saleprice: 899.99,
    quantity: 1,
    about:
      "An iconic modern chair with a sleek and timeless design, ideal for any contemporary space.",
  },
  {
    id: 15,
    image: "/productpic/thumbnail (14).png",
    title: "Wooden Bathroom Sink With Mirror",
    category: "Furniture",
    price: 450.0,
    saleprice: 499.99,
    quantity: 1,
    about:
      "A high-quality wooden sink with a built-in mirror, combining elegance and functionality for your bathroom.",
  },
  {
    id: 16,
    image: "/productpic/thumbnail (15).png",
    title: "Apple",
    category: "Furniture",
    price: 2.0,
    saleprice: 4.1,
    quantity: 1,
    about:
      "A high-quality wooden sink with a built-in mirror, combining elegance and functionality for your bathroom.",
  },
];
